file:
  image-server-url: "http://localhost:8088/foodie/faces/"
  #  image-server-url 会找下面的地址，然后+/foodie/faces/
  image-user-face-location: "/Users/xuzhiwei/开发文件/foodie/"
  image-formats:
    - jpg
    - jpeg
    - png
mybatis:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印，便于开发
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
