file:
  image-server-url: "http://localhost:8088/foodie/faces/"
  #  image-server-url 会找下面的地址，然后+/foodie/faces/
  image-user-face-location: "/Users/xuzhiwei/开发文件/foodie/"
  image-formats:
    - jpg
    - jpeg
    - png
mybatis:
  configuration:
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印，便于开发
spring:
  datasource:
    #    docker定义的内部mysql ip地址
    url: jdbc:mysql://172.16.238.100/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.238.200
    timeout: 6000ms
    #  docker定义的内部redis ip地址
    #  有了哨兵就不需要指定host了
    #  host: 172.16.238.200
    #    timeout: 6000ms
    #    database: 0
    #    sentinel:
    #      master: foodie
    #      nodes:
    #        - 172.16.238.210:26379
    #        - 172.16.238.211:26379
    #        - 172.16.238.212:26379
    #    cluster:
    #      nodes:
    #        - 172.16.238.210:6379
    #        - 172.16.238.211:6379
    #        - 172.16.238.212:6379
    #        - 172.16.238.213:6379
    #        - 172.16.238.214:6379
    #        - 172.16.238.215:6379