#执行器配置文件
server:
  port: 8081

logging:
  config: classpath:logback.xml

spring:
  datasource:
    #    docker定义的内部mysql ip地址
    url: jdbc:mysql://localhost:3306/foodie-shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

xxl:
  job:
    accessToken:
    admin:
      addresses: http://127.0.0.1:8090/xxl-job-admin
    executor:
      appname: xxl-rabbit-message-executor
      ip:
      port: 9999
      logpath: ./data/applogs/xxl-job/jobhandler
      logretentiondays: 7
